version: '2'
services:
    jhipsterexample-app:
        image: jhipsterexample
        external_links:
            - jhipsterexample-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/jhipsterexample?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterexample-mysql:
        extends:
            file: mysql.yml
            service: jhipsterexample-mysql
